### ISSUE TITLE
ERROR IN RESUME LINK

### ISSUE THREAD

**Issue by SHAKUURR** [Ibanez92/Responsive_Portfolio#1]
Hi Ibanez, 
I must say, your portfolio site is really amazing sand unique. You've got amazing stuff on it. However, I would love you to kindly recheck the ABOUT section, the link which says; _check out my resume_ is showing error 404 when clicked. Kindly look into it. 
![Screenshot (207)](https://user-images.githubusercontent.com/108751084/229852340-1c23a852-da2c-4b72-b499-f8d97ed07ab1.png)

**Comment by Ibanez92** [comment]
Hello,

thank you so much for getting in touch with me. I am currently working on
an updated version of my resume as I will be looking for work soon. Please
feel free to connect with me.

Thanks again,
Javier Ibanez
